disabled_rules: # Rule identifiers to exclude from running
  - line_length # Documentation can exceed line lengths
  - identifier_name
  - force_unwrapping
  - force_cast
  - force_try
  - orphaned_doc_comment
  - opening_brace
  - switch_case_alignment
  - trailing_comma
  - todo
opt_in_rules:
  - block_based_kvo
  - class_delegate_protocol
  - contains_over_first_not_nil
  - convenience_type
  - empty_count
  - empty_string
  - explicit_init
  - fallthrough
  - fatal_error_message
  - first_where
  - identical_operands
  - joined_default_parameter
  - object_literal
  - operator_usage_whitespace
  - overridden_super_call
  - private_outlet
  - prohibited_super_call
  - redundant_nil_coalescing
  - switch_case_on_newline
  - toggle_bool
  - type_contents_order
  - multiline_function_chains
syntactic_sugar: error
unused_closure_parameter: error
unused_optional_binding: 
  severity: error
file_length:
  warning: 600
  error: 1200
function_body_length:
  warning: 50
  error: 70
type_body_length:
  warning: 300
  error: 400
type_name:
  max_length: # warning and error
    warning: 50
    error: 60
object_literal:
  color_literal: false
type_contents_order:
  order:
    - case
    - subtype
    - associated_type
    - type_alias
    - ib_outlet
    - ib_inspectable
    - type_property
    - [initializer, instance_property]
    - view_life_cycle_method
    - [subscript, other_method, ib_action]
    - type_method

included:
  - ${SRCROOT}
  - ${SRCROOT}/../Sources
  - ${SRCROOT}/../../Sources
excluded:
  # We add ../../../ to work with the way Danger is expanding paths based on the config file.
  - ${SRCROOT}/Carthage
  - ${SRCROOT}/.build
  - ${SRCROOT}/Playgrounds
  - ${SRCROOT}/Submodules
  - ${SRCROOT}/SourcePackages
  - ${SRCROOT}/*/SourcePackages
  - ${SRCROOT}/*/*/SourcePackages
  - ${SRCROOT}/*/*/*/SourcePackages
  - ${SRCROOT}/Vendor
  - ${SRCROOT}/Pods
  - ${SRCROOT}/bundle
  - ${SRCROOT}/scripts/genstrings.swift
  - ${SRCROOT}/danger/DangerTests.swift
  - ${SRCROOT}/*UITests
  - ${SRCROOT}/Tests
  - ${SRCROOT}/*Tests
  - ${SRCROOT}/*/Tests
  - ${SRCROOT}/.rbenv
  - ${SRCROOT}/*/*/*/*/main.swift # App Store Connect SDK structure
  - ${SRCROOT}/*/*/Tests # App Store Connect SDK structure
