# rubocop:disable LineLength

require "uri"

desc 'Runs tests for a specific package'
lane :test_package do |options|	
	# Set timeout to prevent xcodebuild -list -project to take to much retries.
	ENV["FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT"] = "120"
	ENV["FASTLANE_XCODE_LIST_TIMEOUT"] = "120"

	begin
		reports_dir = "#{ENV['PWD']}/build/reports"

		ENV["XCPRETTY_JSON_FILE_OUTPUT"] = "#{reports_dir}/#{options[:package_name]}_Tests.json"

		# This does not work yet, see: https://github.com/fastlane/fastlane/issues/17734
		# device = options[:device] || "iPhone 11"
		# scan(
		#   scheme: options[:package_name],
		#   xcodebuild_command: "cd #{ENV['PWD']}/#{options[:package_path]} && env NSUnbufferedIO=YES xcodebuild",
		#   device: device,
		#   code_coverage: true,
		#   disable_concurrent_testing: true,
		#   fail_build: false,
		#   skip_slack: true,
		#   output_types: "",
		#   prelaunch_simulator: true,
		#   xcargs: "-UseNewBuildSystem=YES",
		#   include_simulator_logs: false, # Needed for this: https://github.com/fastlane/fastlane/issues/8909
		#   formatter: "xcpretty-json-formatter",
		#   result_bundle: true,
		#   output_directory: "build/reports/",
		#   cloned_source_packages_path: "SourcePackages",
		#   disable_package_automatic_updates: true
		# )

		destination = 'platform=iOS Simulator,name=iPhone 11'
		sourcePackagesDir = "#{ENV['PWD']}/SourcePackages"

		disable_automatic_package_resolution = options.fetch(:disable_automatic_package_resolution, true)
		extra_flags = disable_automatic_package_resolution ? "-disableAutomaticPackageResolution" : ""

		# Set the result bundle path and delete an existing one if needed.
		result_bundle_path = "#{reports_dir}/#{options[:package_name]}.xcresult"
		FileUtils.remove_dir(result_bundle_path) if File.exist?(result_bundle_path)

		#sh "cd #{ENV['PWD']}/#{options[:package_path]} && xcodebuild -showBuildSettings -clonedSourcePackagesDirPath #{sourcePackagesDir} -verbose"
	    sh "cd #{ENV['PWD']}/#{options[:package_path]} && xcodebuild -scheme #{options[:package_name]} -destination '#{destination}' -verbose -resultBundlePath '#{result_bundle_path}' -disable-concurrent-testing -enableCodeCoverage YES -UseNewBuildSystem=YES -clonedSourcePackagesDirPath #{sourcePackagesDir} #{extra_flags} test | xcpretty -f `xcpretty-json-formatter`"
	rescue => ex
		UI.important("Tests failed for #{ex}")
	end
end

desc 'Runs tests for an external project'
lane :test_project do |options|
	clear_derived_data

	# Set timeout to prevent xcodebuild -list -project to take to much retries.
	ENV["FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT"] = "120"
	ENV["FASTLANE_XCODE_LIST_TIMEOUT"] = "120"

	begin
		ENV["XCPRETTY_JSON_FILE_OUTPUT"] = "build/reports/#{options[:scheme]}_Tests.json"

		device = options[:device] || "iPhone 11"
		scan(
		  scheme: options[:scheme],
		  project: "#{options[:project_path]}#{options[:project_name]}.xcodeproj",
		  device: device,
		  destination: options[:destination],
		  code_coverage: true,
		  disable_concurrent_testing: true,
		  fail_build: false,
		  skip_slack: true,
		  output_types: "",
		  prelaunch_simulator: true,
		  xcargs: "-UseNewBuildSystem=YES",
		  include_simulator_logs: false, # Needed for this: https://github.com/fastlane/fastlane/issues/8909
		  formatter: "xcpretty-json-formatter",
		  result_bundle: true,
		  output_directory: "build/reports/",
		  cloned_source_packages_path: "SourcePackages"
		)
	rescue => ex
		UI.important("Tests failed for #{ex}")
	end
end

desc 'Tests the WeTransferPRLinter Swift Package'
lane :test_pr_linter do |options|
	spm(command: "generate-xcodeproj", package_path: "Danger-Swift")
	test_project(
		project_path: "Danger-Swift/", 
		project_name: "WeTransferPRLinter", 
		scheme: "WeTransferPRLinter-Package",
		device: nil,
		destination: "platform=macOS")
end

desc "Returns true if there are new changes since the last available tag"
lane :is_changed_since_last_tag do
  sh "git fetch --tags origin #{ENV["BITRISE_GIT_BRANCH"]} --no-recurse-submodules"
  last_tag = last_git_tag
  changes = sh "git diff --name-only HEAD #{last_tag}"
  puts "Is local HEAD changed since last tag #{last_tag}: #{!changes.empty?}"
  is_changed = !changes.empty?
end

desc 'Create a release from a tag triggered CI run'
lane :release_from_tag do |options|
	# Get the latest tag, which is the new release that triggered this lane.
	sh('git fetch --tags origin master --no-recurse-submodules -q')

	latest_tag = ENV["BITRISE_GIT_TAG"]
	
	# Create a release branch
	sh "git branch release/#{latest_tag} origin/master"
    sh "git checkout release/#{latest_tag}"
    sh "git merge -X theirs #{latest_tag}"

	release_output = sh('gitbuddy release -c "../Changelog.md"')
	release_url = URI.extract(release_output).find { |url| url.include? 'releases/tag' }
    puts "Created release with URL: #{release_url}"

	# Run only if there's a podspec to update
	if Dir['../*.podspec'].any?
		# Update the podspec. It finds the .podspec automatically in the current folder.
		version_bump_podspec(version_number: latest_tag)
		
		begin
			# Push the podspec to trunk
			pod_push
		rescue => ex
			UI.important("Pod push failed: #{ex}")
		end
	end 

	# Push the changes to the branch
	sh('git commit -a -m "Created a new release"')
    sh("git push origin release/#{latest_tag}")
	
	# Create a PR
    # Create a pull request for master to include the updated Changelog.md and podspec
    create_pull_request(
      api_token: ENV["DANGER_GITHUB_API_TOKEN"],
      repo: git_repository_name,
      title: "Merge release #{latest_tag} into master",
      base: "master", # The branch to merge the changes into.
      body: "Containing all the changes for our [**#{latest_tag} Release**](#{release_url})."
    )
end

desc "Unhide dev dependencies for danger"
lane :unhide_spm_package_dev_dependencies do 
	text = File.read('../Package.swift')
	new_contents = text.gsub('// dev ', "")

	# To write changes to the file, use:
	File.open('../Package.swift', "w") {|file| file.puts new_contents }
end

desc "Returns the repository name. E.g: WeTransfer/Mocker"
lane :git_repository_name do
	sh("git remote show origin -n | grep h.URL | sed 's/.*://;s/.git$//'").strip
end

desc "Get latest release from Github. Draft releases and prereleases are not returned by this endpoint. See: https://developer.github.com/v3/repos/releases/#get-the-latest-release"
lane :latest_github_release do
	origin_name = git_repository_name.split('/')
	organisation = origin_name[0]
	repository = origin_name[1]

	result = github_api(
		server_url: "https://api.github.com",
		api_token: ENV["DANGER_GITHUB_API_TOKEN"],
		http_method: "GET",
		path: "/repos/#{organisation}/#{repository}/releases/latest"
	)

	puts "Latest Github release is #{result[:json]["tag_name"]}"
	result[:json]["tag_name"]
end

desc "Get all changed files in the current PR"
lane :changed_files_in_pr do |options|
	origin_name = git_repository_name.split('/')
	organisation = origin_name[0]
	repository = origin_name[1]

	if options[:pr_id].nil?
		raise "Missing PR ID input"
	elsif ENV["DANGER_GITHUB_API_TOKEN"].nil?
		raise "Missing 'DANGER_GITHUB_API_TOKEN' environment variable"
	end

	puts "Fetching changed files for PR #{options[:pr_id]} using token ...#{ENV["DANGER_GITHUB_API_TOKEN"].chars.last(5).join}"

	result = github_api(
		server_url: "https://api.github.com",
		api_token: ENV["DANGER_GITHUB_API_TOKEN"],
		http_method: "GET",
		path: "/repos/#{organisation}/#{repository}/pulls/#{options[:pr_id]}"
	)

	baseRef = result[:json]["base"]["ref"]

	# As CI fetches only the minimum we need to fetch the remote to make diffing work correctly.
	sh 'git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"'
	sh "git fetch --no-recurse-submodules --no-tags"
	sh "git diff --name-only HEAD origin/#{baseRef}"
end

desc "Check whether any of the changes happened in the given path"
lane :pr_changes_contains_path do |options|
  changes_contains_path = options[:changed_files].include?(options[:path])

  if changes_contains_path
  	puts "Changes found for path #{options[:path]}"
  elsif
	puts "No changes found for path #{options[:path]}"
  end
  	
  changes_contains_path
end

desc "Updates the build number of the project based on the commit count"
desc ""
desc "#### Options"
desc " * **`xcodeproj`**: the path to the Xcode project to read the version number from"
desc " * **`target`**: The target within the project to read the version number from"
desc ""
lane :update_build_number do |options|
	# Get the path to the Xcode project and the target to read the version number from.
	xcodeproj = options[:xcodeproj]
	target = options[:target]

  # Compute a new build number based on the commit count.
	build = sh "git rev-list --all --count"
  new_build_number = 200 + Integer(build)

	# Fetch the build number of the most recent test flight build, to make sure
	# that the new build number will be higher.
  version_number = get_version_number(xcodeproj: xcodeproj, target: target)
  latest_app_store_build_number = latest_testflight_build_number
  test_flight_build_number = latest_testflight_build_number(version: version_number)

  if new_build_number <= latest_app_store_build_number
    puts "git build number is smaller than the build number of the latest release"
    puts "Using the latest release build number #{latest_app_store_build_number} + 1"
    new_build_number = latest_app_store_build_number + 1
  end

  if new_build_number <= test_flight_build_number
    puts "git build number is smaller than test flight build number"
    puts "Using the TestFlight build number #{test_flight_build_number} + 1"
    new_build_number = test_flight_build_number + 1
  end

  increment_build_number(build_number: new_build_number)
end

desc "Syncs production certificates on CI"
desc ""
desc "#### Options"
desc " * **`app_identifier`**: a list of all app identifiers for which to sync the certs"
desc ""
lane :certs do |options|
  # Create Keychain to store certificates in
  create_keychain(
    name: ENV["MATCH_KEYCHAIN_NAME"],
    password: ENV["MATCH_KEYCHAIN_PASSWORD"],
    default_keychain: true,
    unlock: true,
    timeout: 3600,
    add_to_search_list: true)
  # Sync certificates
  match(
    keychain_name: "#{ENV["MATCH_KEYCHAIN_NAME"]}",
    keychain_password: "#{ENV["MATCH_KEYCHAIN_PASSWORD"]}",
    app_identifier: options[:app_identifier],
    force: true,
    type: "appstore")
end

desc "Fetch the version number we're preparing to release in App Store Connect"
desc ""
desc "#### Options"
desc " * **`fastlane_team_id`**: the identifier of your Apple developer team"
desc " * **`fastlane_itc_team_id`**: the identifier of the App Store Connect team"
desc " * **`app_identifier`**: the bundle identifier of the app for which to fetch the preparing version number"
desc ""
lane :current_preparing_app_version do |options|
  puts 'fetching highest version on App Store Connect...'

  ENV["FASTLANE_TEAM_ID"] = options[:fastlane_team_id]
	ENV["FASTLANE_ITC_TEAM_ID"] = options[:fastlane_itc_team_id]

  token = Spaceship::ConnectAPI::Token.create(Actions.lane_context[SharedValues::APP_STORE_CONNECT_API_KEY])
  Spaceship::ConnectAPI.token = token

  app = Spaceship::ConnectAPI::App.find(options[:app_identifier])

  if app.nil?
    puts 'App not found'
    next
  end

  puts "Found app #{app.name}"

  if app.get_edit_app_store_version.nil?
    puts 'No edit app store version found'
    next
  end

  puts "Latest edit version is #{app.get_edit_app_store_version.version_string}"

  app.get_edit_app_store_version.version_string
end

desc "Ensures that a new release is allowed to happen"
desc ""
desc "#### Options"
desc " * **`version_number`**: The version number of the project"
desc " * **`tag_name`**: The name of the latest release on GitHub"
desc " * **`fastlane_team_id`**: the identifier of your Apple developer team"
desc " * **`fastlane_itc_team_id`**: the identifier of the App Store Connect team"
desc " * **`app_identifier`**: the bundle identifier of the app for which to fetch the preparing version number"
desc ""
lane :ensure_release_is_needed do |options|
  preparing_app_version = current_preparing_app_version

  if preparing_app_version.nil?
    message = 'Weekly release cancelled as App Store Connect does not contain a preparing app version'
    UI.important message
    slack(
      message: message,
      success: false,
      default_payloads: [:git_branch, :last_git_commit_message]
    )

    raise message
  end

  local_project_version_number = Gem::Version.new(options[:version_number])
  tag_version_number = Gem::Version.new(options[:tag_name].split('b')[0])

	app_store_preparing_version_string = current_preparing_app_version(
		fastlane_team_id: options[:fastlane_team_id],
		fastlane_itc_team_id: options[:fastlane_itc_team_id],
		app_identifier: options[:app_identifier]
	)

  app_store_preparing_version = Gem::Version.new(app_store_preparing_version_string)

  project_version_is_newer = tag_version_number < local_project_version_number
  preparing_version_is_newer = tag_version_number < app_store_preparing_version

	# Cancel when did not manage to create a stable release on GitHub or when the App Store Connect preparing version doesn't match the project version.
  if project_version_is_newer || preparing_version_is_newer
    UI.important "Release cancelled. Tag version: #{tag_version_number}, project version: #{local_project_version_number}, app store preparing version: #{app_store_preparing_version}"

    slack(
      message: "Weekly released cancelled as no new green light build is available.",
      success: false,
      default_payloads: [:git_branch, :last_git_commit_message],
      payload: {
        "Latest available release tag" => tag_version_number
      }
    )

    raise "Weekly released cancelled as no new green light build is available."
  end
end

desc "Get latest release from Github that is not a prelease or release candidate"
lane :latest_github_non_candidate_tag do
  origin_name = git_repository_name.split('/')
  organisation = origin_name[0]
  repository = origin_name[1]

  result = github_api(
    server_url: "https://api.github.com",
    api_token: ENV["DANGER_GITHUB_API_TOKEN"],
    http_method: "GET",
    path: "/repos/#{organisation}/#{repository}/releases"
  )
  latest_release = result[:json].find { |release| !release["name"].downcase.include? "candidate" }
  latest_release["tag_name"]
end

desc "Strips Markdown URLs and returns it as plain text"
desc "Used for example for the App Store changelog"
desc "#### Options"
desc " * **`input`**: The text from which to strip the Markdown URLs"
lane :strip_markdown_url do |options|
  options[:input].gsub(/(?:__|[*#])|\[(.*?)\]\(.*?\)/, '\1')
end
