# This SwiftLint file is used for Tests
disabled_rules: # Rule identifiers to exclude from running
  - line_length # Documentation can exceed line lengths
  - force_unwrapping
  - force_try
  - force_cast
  - type_name
  - type_body_length
  - file_length
  - identifier_name
  - function_body_length
  - nesting
opt_in_rules:
  - empty_count
  - explicit_init
  - first_where
  - object_literal
  - operator_usage_whitespace
  - overridden_super_call
  - private_outlet
  - prohibited_super_call
  - redundant_nil_coalescing
  - switch_case_on_newline
operator_usage_whitespace: error
syntactic_sugar: error
trailing_comma: 
  severity: error
trailing_newline: error
trailing_semicolon: error
trailing_whitespace: error
unused_closure_parameter: error
unused_optional_binding: 
  severity: error
vertical_whitespace: 
  severity: error
object_literal:
  color_literal: false
trailing_whitespace:
  ignores_empty_lines: true # This is such a hassle to do right and adds nothing

excluded:
  - ${SRCROOT}/Carthage
  - ${SRCROOT}/Playgrounds
  - ${SRCROOT}/Submodules
  - ${SRCROOT}/scripts/genstrings.swift
  - ${SRCROOT}/danger/DangerTests.swift
  - ${SRCROOT}/${PROJECT_NAME}
  - ${SRCROOT}/Sources # Folder for open source projects